// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/properties-panel/Background.vue')['default']
    Border: typeof import('./src/components/properties-panel/Border.vue')['default']
    ColorPicker: typeof import('./src/components/properties-panel/ColorPicker.vue')['default']
    ComponentLayer: typeof import('./src/components/ComponentLayer.vue')['default']
    ComponentTemplate: typeof import('./src/components/ComponentTemplate.vue')['default']
    DataSource: typeof import('./src/components/DataSource.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper/EditWrapper.vue')['default']
    Font: typeof import('./src/components/properties-panel/Font.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageProcessor: typeof import('./src/components/properties-panel/ImageProcessor.vue')['default']
    InlineEdit: typeof import('./src/components/InlineEdit.vue')['default']
    Monaco: typeof import('./src/components/Monaco.vue')['default']
    MoreUploader: typeof import('./src/components/MoreUploader.vue')['default']
    Padding: typeof import('./src/components/properties-panel/Padding.vue')['default']
    PhoneView: typeof import('./src/components/PhoneView.vue')['default']
    Position: typeof import('./src/components/properties-panel/Position.vue')['default']
    PreSetting: typeof import('./src/components/PreSetting.vue')['default']
    PropertiesPanel: typeof import('./src/components/PropertiesPanel.vue')['default']
    Size: typeof import('./src/components/properties-panel/Size.vue')['default']
    SourceKey: typeof import('./src/components/SourceKey.vue')['default']
    StyledUploader: typeof import('./src/components/StyledUploader.vue')['default']
    TableSet2: typeof import('./src/components/TableSet2.vue')['default']
    Tinymce: typeof import('./src/components/Tinymce.vue')['default']
    Uploader: typeof import('./src/components/Uploader.vue')['default']
  }
}

export { }
